### ISSUE TITLE
Refactored everything

### ISSUE THREAD

**Issue by thesummit** [magnolia1234/bypass-paywalls-chrome-clean#50]
Hey!

Saw your post on HN.

I just spent all afternoon and was was able to refactor and modernize the entirety of the original project. Much cleaner code. However, to my dismay, I found out the "PRs are welcome" was a lie only after I completed the overhaul.

I wanted to submit that PR here but it looks like your fork has deviated from the original a bit already. It might be easier and more productive if you applied your new changes to the refactored and clean version of this project found here: https://github.com/thesummit/bypass-paywalls-chrome

Would you mind collaborating by submitting a PR on top of my project there? I can then add you as an admin to the project since I'm not super interested in maintaining the project myself.

Cheers!

**Comment by magnolia1234** [comment]
Interesting, a reverse PR offer ;-)
If you're interested to make a PR, you're welcome (or else I can use some changes in the future).
My hard fork/mirror has actually progressed instead of 'deviated' from Adam's repo: a lot more sites, bug-fixes and the option for custom sites.

I've checked the commit in your 'modernize'-branch.
You've cleaned up the code of background.js and contentScript.js with some class-functions and updated array-functions, but also a lot of (cosmetic) changes in variable-names and styling.
The list of sites and rules in contentScript.js is interesting, but you check isHrefMatch for all the sites now, but not all of them (i.e. more complicated fixes) are in this list (just the simple ones).

**Comment by magnolia1234** [comment]
PS my clean stands for no Google Analytics (still in your branch though).

**Comment by danielgruber8** [comment]
What is HN? Hacker News?

**Comment by magnolia1234** [comment]
@thesummit 
Error in event handler: TypeError: changes.filter is not a function (background.js:303)
contentScript.js is indeed not working for example on nzherald.co.nz etc.

**Comment by magnolia1234** [comment]
> What is HN? Hacker News?

Yeah, some joker made a submission about BPC ;-)

**Comment by thesummit** [comment]
I finished refactoring but didn't begin testing once I found out it didn't have a place to live. If you intend to submit a PR, I can make you admin, test it, and fix any bugs. 

Is that what you're intending to do?

**Comment by thesummit** [comment]
yeah I stopped working on it after I found out it had no place to go.

**Comment by danielgruber8** [comment]
This project keeps getting better :)

**Comment by magnolia1234** [comment]
> I finished refactoring but didn't begin testing once I found out it didn't have a place to live. If you intend to submit a PR, I can make you admin, test it, and fix any bugs.
Is that what you're intending to do?

@thesummit 
No thanks, I'll stick to my own repo.
But I see you did make a PR here now.
